<?php

namespace Database\Seeders;

use App\Models\Matrix;
use Illuminate\Database\Seeder;

class MatrixSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $matrixes = [
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 1,
                'value'             => 1.592, 
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 2,
                'value'             => 2.778,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 3,
                'value'             => 2.778,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 5,
                'value'             => 2.471,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 1,
                'colNo_kriteria'    => 8,
                'value'             => 3.082,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 1,
                'value'             => 0.372,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 2,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 3,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 5,
                'value'             => 3.024,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 2,
                'colNo_kriteria'    => 8,
                'value'             => 3.521,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 1,
                'value'             => 2.411,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 2,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 3,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 5,
                'value'             => 3.23,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 3,
                'colNo_kriteria'    => 8,
                'value'             => 1.361,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 1,
                'value'             => 0.558,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 2,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 3,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 5,
                'value'             => 3.754,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 4,
                'colNo_kriteria'    => 8,
                'value'             => 1.361,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 1,
                'value'             => 2.411,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 2,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 3,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 5,
                'value'             => 3.623,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 5,
                'colNo_kriteria'    => 8,
                'value'             => 1.361,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 1,
                'value'             => 2.722,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 2,
                'value'             => 2.478,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 3,
                'value'             => 2.778,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 5,
                'value'             => 1.476,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 7,
                'value'             => 0,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 6,
                'colNo_kriteria'    => 8,
                'value'             => 3.521,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 1,
                'value'             => 0.372,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 2,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 3,
                'value'             => 0.556,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 4,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 5,
                'value'             => 1.771,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 6,
                'value'             => 0,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 7,
                'colNo_kriteria'    => 8,
                'value'             => 1.361,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 1,
                'value'             => 1.651,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 2,
                'value'             => 2.778,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 3,
                'value'             => 1.523,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 4,
                'value'             => 0,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 5,
                'value'             => 1.724,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 6,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 7,
                'value'             => 1,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'rowNo_alternatif'  => 8,
                'colNo_kriteria'    => 8,
                'value'             => 1.361,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ];

        Matrix::insert($matrixes);
    }
}
